---
deployment:
	tasks:
    - export DEPLOYPATH=/home/running/public_html/
		- export REPOPATH=/home/running/repositories/rrc-website/
    - /bin/rm -Rf ${DEPLOYPATH}_old
    - /bin/cp -R ${DEPLOYPATH} ${DEPLOYPATH}_old
		- /bin/rsync -aP --exclude '.git' --exclude '.well-known' ${REPOPATH}/ ${DEPLOYPATH} --delete-after